language: 
    -cpp
    -android
    
#For Android    
# Handle git submodules yourself
git:
    submodules: false

#For Android
install:
# NDK configuration
    - printenv
    - echo `pwd`
    - wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin
    - chmod a+x android-ndk-r10d-linux-x86_64.bin
    - ./android-ndk-r10d-linux-x86_64.bin -y | grep -v Extracting # because log will be too long!
    - export NDK_ROOT=`pwd`/android-ndk-r10d
    - echo $NDK_ROOT
    - export PATH=$PATH:$NDK_ROOT
    - echo $PATH  
# Android SDK configuration
    - export ANDROID_SDK_ROOT=/usr/local/android-sdk
    - export PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools
# git submodule
# Use sed to replace the SSH URL with the public URL, then initialize submodules
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
# cocos setup 
    - cd ./cocos2d
    - python download-deps.py --remove-download=yes
    - python ./setup.py
    - export COCOS_CONSOLE_ROOT=`pwd`/tools/cocos2d-console/bin
    - export PATH=$PATH:$COCOS_CONSOLE_ROOT
    - export COCOS_TEMPLATES_ROOT=`pwd`/templates
    - export PATH=$PATH:$COCOS_TEMPLATES_ROOT
    - export ANT_ROOT=/usr/share/ant/bin
    - export PATH=$PATH:$ANT_ROOT
    - printenv

env:
  matrix:
  - GEN_JSB=YES
  - PLATFORM=linux DEBUG=1
  # Since switching to C++11 only the ARM version of the nactive client
  # port currently builds.  TODO(sbc): Re-enable all architectures.
  # Disabled travis-ci build for native client port since it doesn't support std::thread, std::mutex.
  # - PLATFORM=nacl DEBUG=1 NACL_ARCH=arm
  - PLATFORM=android
  # - PLATFORM=emscripten DEBUG=1
  global:
  - secure: |-
      cHXOjAda+t2tmBVuVAiQfvhDN+unToO6hX1rc3dJeGDOk4rlQnylJacjA7o/
      enkWeHagbW2Ja4h7BxQz4h7dada8zEbIbEMK4VEHx6AWwQM+GIEqkJPv5g8k
      4P20MLpX4XyUwm/16btpnqgXlyd8Q3Zjh3Vui/5/VzwPnxUQEho=
  - secure: |-
      U/JsyiSR9q+8wX1arfciy3BdbMQaKmgt48/9tiU7P2RQJ/FR2AHGq85sNGI/
      ZUxN4JPLGALEvkFMo4NYyJDUcsdRHZX3vbp5xbSSRaBigqJIj3HDxtlPVf2m
      /W2GzcfNNX1ACO18hSWH0d2yFlF263ZmvudzQIfqTESfjGQBzwA=
  - secure: |-
      Wsngwo3jlZtvuPfr3RNhqrz/liNIhKYnlw4KYJO90gMQ9ZQKRTlMv2BMiPw/
      9lV+vgJQDRcFe7dKwtC86vk10EU7Ym2bhVmhMxi/AlmJXgavjmPVdizRT7rh
      X2Ry/Nb6hGRkH3WS0T3D/KG1+e7lP/TMB9bvo6/locLJ2A6Z1YI=
script:
##CPP
- tools/travis-scripts/run-script.sh
##Android
    - cd ..
    - cocos compile -p android -j 8
before_install:
- tools/travis-scripts/before-install.sh